### ISSUE TITLE
Distributed Input

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/octotiger#161]
Octotiger should have an mechanism to provide several input files for the restart and not all nodes should read one file.

**Comment by diehlpk** [comment]
@khuck Could you please elaborate the approach you were mentioning during the calls and on the mailing list?

**Comment by khuck** [comment]
@diehlpk I had suggested using the [ADIOS2](https://github.com/ornladios/ADIOS2) library - it is a parallel I/O library that has really great scaling performance.  If desired, it can also do timestep based output, and it can do asynchronous staged I/O.

**Comment by diehlpk** [comment]
@khuck We should discuss at our next meeting how we want to improve the IO. I like the idea to use a library and not coding the IO by our own. @dmarce1 What do you think?
