### ISSUE TITLE
After regriding the memory increases 

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/octotiger#162]
Running the v1309 more than 15 time steps and regriding happens, the amount of memory grows after some regridings and it does not fit in the memory any more. So it is not possible to run the level fitting in the memory for longer time steps.

`slurm-12631276.out:src/central_freelist.cc:333] tcmalloc: allocation failed 8192 `

**Comment by diehlpk** [comment]
maybe related to #53

**Comment by dmarce1** [comment]
I will add a new switch to turn off AMR and instead have FMR (fixed mesh refinement) - meaning no regridding. But then we wouldn't be including regridding in the scaling timings.

**Comment by diehlpk** [comment]
I think we should check why the memory increases so much, because adding some sub-grids shoudl not consume so much memory. I think there is some bug in octotiger or HPX and we do not free memory.

**Comment by diehlpk** [comment]
@khuck What was the name of the profiler you mentioned last time?

**Comment by khuck** [comment]
@diehlpk https://github.com/KDE/heaptrack
