### ISSUE TITLE
Vc CMake Switch not Working

### ISSUE THREAD

**Issue by aserio** [STEllAR-GROUP/octotiger#204]
## Expected Behavior

I should be able to compile Octo-Tiger without Vc thus not needing to install the Vc libraries

## Actual Behavior

When building I received this message: 

> In file included from /home/aserio/git/octotiger/src/compute_factor.cpp:6:
> /home/aserio/git/octotiger/octotiger/common_kernel/kernel_simd_types.hpp:8:10: fatal error: > Vc/Vc: No such file or directory
> #include <Vc/Vc>
>                 ^~~~~~~
>compilation terminated.
> make[2]: *** [CMakeFiles/octolib.dir/src/compute_factor.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....

## Steps to Reproduce the Problem

I ran the following commands on Rostam:

cmake -DHPX_DIR=/home/aserio/lib/master-gcc8.3.0/lib64/cmake/HPX/ \
-DCMAKE_BUILD_TYPE=Debug -DSilo_LIBRARY=/opt/mn/silo/4.10.2/lib \
-DSilo_INCLUDE_DIR=/opt/mn/silo/4.10.2/include \
-DSilo_BROWSER=/opt/mn/silo/4.10.2/bin \
-DOCTOTIGER_WITH_Vc=OFF ..

make -j

## Specifications

  - HPX Version: 079729f
  - Platform: Tycho (Rostam)

**Comment by diehlpk** [comment]
Since we did some redesign of the VC stuff, we will close this issues for now.
