### ISSUE TITLE
simd_vector should use scalar-vector ops instead of converting scalars to vectors

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/octotiger#24]
Currently, scalars are converted to vectors and vector-vector operations are used scalars and vectors are mixed. simd_vector should be updated to use actual scalar-vector intrinsics and the appropriate overloads should be added.

**Comment by hkaiser** [comment]
I don't think we should start modifying the original  simd_vector  implementation. We should move entirely to the Vc library.
