### ISSUE TITLE
simd_vector should be constexpr

### ISSUE THREAD

**Issue by brycelelbach** [STEllAR-GROUP/octotiger#25]
simd_vector should have a constexpr constructor and possibly constexpr operations.

**Comment by hkaiser** [comment]
I don't think we should start modifying the original `simd_vector` implementation. We should move entirely to the Vc library.

**Comment by brycelelbach** [comment]
Currently simd_vector is used both to implement vector paralleism, **and** to represent a vector of 8 elements. Do we intend for the Vc datatype to play this dual role as well?

I'd prefer to keep simd_vector around for now, until we have the KNL avx512 support in Vc. Alternatively, I could switch my focus to making that happen ASAP.
