### ISSUE TITLE
Faulty timers

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/octotiger#254]
The timers in the current master version of Octo-Tiger (199addb3cbcf31aead2cc6a9fea43cb871d5c358)are not working correctly from what I can see.

I am running the rotating star scenario:

> ./build/octotiger/build/octotiger -t1 --problem=rotating_star --theta=0.34 --xscale=1.5 --odt=0.1 --stop_time=0.5 --stop_step=3 --max_level=4 --input_file=rotating_star.bin --n_species=5 --multipole_kernel_type=SOA_CPU --p2p_kernel_type=SOA_CPU --p2m_kernel_type=SOA_CPU --cuda_streams_per_locality=0

The resulting timers like like this:

>    Total: 202.94                                                                                                                                                                     
   I/O:         6.42329 (3.16511%)                                                                                                                                                   
   Computation: 182.131 (89.7462%)                                                                                                                                                   
   Gravity:     182.788 (90.07%)                                                                                                                                                     
   Hydro: -0.657052 (-0.00323766%)
   Regrid: 3.90468 (1.92405%)
   Compare Analytic: 10.3547 (5.10235%)
   Find Localities: 0 (0%)

One problem is rather obvious: The hydro timer reports a negative time.

The other problem becomes obvious when looking at the profiler results:
The most compute-intensive method (according to perf) is flux method, followed closely by the reconstruct method. Both of which should be part of the hydro code if I am not mistaken. The gravity timer seems to measure parts of the hydro code as well. Maybe the case of suspending HPX tasks in compute_fmm is not handled properly? Either way, right now the timers and profiler report a vast difference.

**Comment by diehlpk** [comment]
@dmarce1 I think this is fixed with in master or?

**Comment by diehlpk** [comment]
@dmarce1 and @G-071 Is this fixed and can be closed?

**Comment by dmarce1** [comment]
Patrick

Yes it is fixed

Dominic
