### ISSUE TITLE
Linking error:  undefined reference to `physics<2>::field_names2'

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/octotiger#272]
## Expected Behavior

Should link 

## Actual Behavior

```
CMakeFiles/unitiger.dir/src/unitiger/main.cpp.o:(.toc+0x20): undefined reference to `physics<2>::field_names2'
/usr/bin/ld: link errors found, deleting executable `unitiger'
collect2: error: ld returned 1 exit status
gmake[2]: *** [unitiger] Error 1
```

## Steps to Reproduce the Problem

Compile today's master

## Specifications

... Please describe your environment

  - HPX Version: 1.4
  - Platform (compiler, OS): gcc 8.1.1 boost 1.78.0

**Comment by G-071** [comment]
I have encountered the same issue! It should be fixed in #276
