### ISSUE TITLE
Octotiger crashes on cori KNL

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/octotiger#28]
When I run on cori @ NERSC, I get this transient error in gdb (which I had to build myself):

```
...
-----------------------------------------------
---------------Created Level 2---------------

-----------------------------------------------
checking for refinement

Thread 8 "octotiger" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x2aaab87d9700 (LWP 170780)]
node_server::check_for_refinement (this=0x2aaacae6ca20)
    at /project/projectdirs/xpress/hpx-lsu-cori-II/src/octotiger/src/node_server_actions_2.cpp:24
24	    if (is_refined) {
(gdb) list
19	}
20	
21	bool node_server::check_for_refinement() {
22	    bool rc = false;
23	    std::vector<hpx::future<bool>> futs;
24	    if (is_refined) {
25	        futs.reserve(children.size());
26	        for (auto& child : children) {
27	            futs.push_back(child.check_for_refinement());
28	        }
(gdb) print is_refined
$1 = 128
(gdb) whatis is_refined
type = bool
```

**Comment by hkaiser** [comment]
How did you build it? 
What command line options?

**Comment by khuck** [comment]
I am putting those instructions in the wiki now...

**Comment by khuck** [comment]
the sequence I used to cause this bug is on this page: https://github.com/STEllAR-GROUP/octotiger/wiki/Build-Instructions#build-instructions-for-hpx-with-apex-and-octotiger-on-corinersc-for-the-knls

**Comment by hkaiser** [comment]
@khuck Thanks for the detailed build instructions. Some comments:

- in order for HPX to be able to run on more than 64 processing units you need to add `-DHPX_WITH_MORE_THAN_64_THREADS=On` while configuring HPX
- Vc (master) does not directly support AVX512 yet. @mattkretz is working on implementing this on his branch: https://github.com/VcDevel/Vc/tree/mkretz/datapar. @brycelelbach reported problems when trying to use the ongoing work from there, but we hope to get it under control asap.

**Comment by khuck** [comment]
@hkaiser The toolchain file that Thomas created for the CrayKNL specifies 512 max threads
```
# We have a bunch of cores on the MIC ... increase the default
set(HPX_WITH_MAX_CPU_COUNT "512" CACHE STRING "")
```
Is that sufficient?  If not, we should add the other setting to the toolchain file.

**Comment by hkaiser** [comment]
@khuck Yes, that should be sufficient. I however would suggest not to use `512` as the max number of processing units. We should use `272` instead (or something rounded up to the nearest multiple of `64 == sizeof(long)`, where `long` is most likely used to hold the bits in the `std::bitset<>` storing the CPU masks in HPX). @sithhell What's you suggestion here?

**Comment by hkaiser** [comment]
@khuck, @sithhell I corrected the max number of processing units in the HPX tool chain file to 320.

**Comment by sithhell** [comment]
On Samstag, 3. Dezember 2016 10:37:35 CET Hartmut Kaiser wrote:
> @khuck, @sithhell I corrected the max number of processing units in the HPX
> tool chain file to 320.
 
Why? The reason to have 512 was to potentially benefit from the AVX512 
instructions.

**Comment by hkaiser** [comment]
@sithhell Sure, if the mask handling can utilize AVX512 this might be beneficial, I however doubt that this would significantly improve performance. I'd rather think that reducing memory bandwidth required for copying the masks around may be more important. But sure, let's do some measurements.

**Comment by sithhell** [comment]
I just compiled a simple test case (using -xmic-avx512 -O3 -S):
```
#include <bitset>

std::bitset<512> and_(std::bitset<512> const& a, std::bitset<512> const& b)
{
    return a & b;
}

std::bitset<320> and_(std::bitset<320> const& a, std::bitset<320> const& b)
{
    return a & b;
}
```

The resulting assembly shows that the 512 bit variant compiles down to two (vector) loads and a single (vector) and resulting in approx. 11 cycles (according to the intel compiler output). While the 320 bit variant results in 35 cycles with scalar 10 loads and 5 ands. Considering that a L1 cache line of a KNL is 64 byte and 2 loads can be done simultaneously, both variants have to load a total of 128 byte, while the first variant is slightly more efficient since it only has to load from cache once.

**Comment by hkaiser** [comment]
@sithell Ok, great. I'll roll back my commit.
