### ISSUE TITLE
Significant increase in the running time of the sod problem

### ISSUE THREAD

**Issue by shibersag** [STEllAR-GROUP/octotiger#280]
The sod problem running significantly longer than it used to be previously.

I attach a configuration file (sod.ini) and four output files. Two output files from simulations ran on BigRed3 (th24 and th24_3) and two from simulations ran on Queen-Bee (th40 and th40_3). I ran the same octotiger commit but with a different hpx version. With hpx 1.4.0 the running time significantly increased (almost by 5).

## Steps to Reproduce the Problem
1. Install octotiger commit aa7519f40c7da80acc1bf3593cd62af2486debb6 with hpx 1.4.0.
2. Run the sod problem test.

1. Install the same octotiger commit but with hpx commit 8e77499f2f243342f13fc546f6e65803d8b2ac94 (earlier than 1.4.0).
2. Run the sod problem test with the same configuration.

See the difference in the running time.
Instead of about 20-30 minutes it goes to more than two hours.
------

It happens both on Queen-Bee and on BigRed3 so it seems to be independent of the specific environment being used.

[sod.ini.LOG](https://github.com/STEllAR-GROUP/octotiger/files/4471827/sod.ini.LOG)
[th40_3.LOG](https://github.com/STEllAR-GROUP/octotiger/files/4471811/th40_3.LOG)
[th40.LOG](https://github.com/STEllAR-GROUP/octotiger/files/4471812/th40.LOG)
[th24_3.LOG](https://github.com/STEllAR-GROUP/octotiger/files/4472136/th24_3.LOG)
[th24.LOG](https://github.com/STEllAR-GROUP/octotiger/files/4472138/th24.LOG)

**Comment by shibersag** [comment]
It was fixed in one of the recent commits.
However, I think that HPX people might be interested to have a look at this problem.

**Comment by diehlpk** [comment]
@shibersag If you want that HPX folks look into this, you should open a new ticket in the HPX repo and refer to this one. 

I will close this ticket for now.
