### ISSUE TITLE
Runs slower with intrasubgrid paralleziation turned on for gravity solver.

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/octotiger#29]
In the most recent commit I added a macro that can turn on or off the parallelism within compute_*interactions* in grid_fmm.cpp and node_server.cpp. On my laptop at least Octotiger runs ~25% *slower* with the parallelism turned ON. This is for the test problem in test2.sh

**Comment by hkaiser** [comment]
From what I can see, this is caused by the need to synchronize the access to `L` and `L_c`.
