### ISSUE TITLE
More documentation for the hotspots would be really helpful

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/octotiger#30]
I'm working on the optimization of some of the hotspots. For this it would be very helpful if more documentation were available to make it easier for me to understand the implemented algorithm.

Based on the current level of optimization, the following functions are most interesting:
- in `taylor.hpp`: `taylor<5, simd_vector>::set_basis`
- in `grid_fmm.cpp`:
  - `grid::compute_interactions`
  - `grid::compute_boundary_interactions_multipole_multipole`
  - `grid::compute_boundary_interactions_monopole_monopole`
  - `grid::compute_boundary_interactions_multipole_monopole`
  - `grid::compute_boundary_interactions_monopole_multipole`
(ordered by their share of runtime)

What would be helpful:
  - Some line comment information would be very useful. Very helpful are comments before loops and non-obvious conditionals. Some explanations for the most important variables are also helpful.
  - It would be useful to know the mathematical formula the taylor expansion is applied to

I selected those hotspots based on experiments of the moving star scenario on my Skylake machine and results shown in the [Optimization progress](https://github.com/STEllAR-GROUP/octotiger/wiki/Optimization-progress) wiki page.

**Comment by diehlpk** [comment]
Here are some [UML diagrams](https://github.com/STEllAR-GROUP/octotiger/wiki/UML-diagramms) for understanding the dependencies better

**Comment by diehlpk** [comment]
I assume the mathematics behind the grid_fmm can be found in this article [Dehnen - A fast multipole method for stellar dynamics](https://arxiv.org/pdf/1405.2255v1.pdf)

**Comment by DavidPfander-UniStuttgart** [comment]
Added some comments with the help of Dominic. (Thanks, Dominic!)
