### ISSUE TITLE
Seg fault at p2m_kernel.cpp line 32

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/octotiger#305]
## Expected Behavior

I expect Octo-Tiger to run at all on my lap top

## Actual Behavior

Octo-Tiger is crashing, no matter what problem I specify,  at line 32 of p2m_kernel.cpp

It started when I upgraded my machine to Ubuntu 19, which changed the gcc version to 9.2.1

Octo-Tiger top of master
HPX 1.4.1
gcc version 9.2.1
Ubuntu 19

**Comment by G-071** [comment]
Hmm that's an odd line for a crash:
```cpp
          , theta_rec_squared(sqr(1.0 / opts().theta)) {
```
I can see it crashing in case opts().theta is 0, but that shouldn't be the case in our scenarios.

Either way, I will to to replicate the crash myself! I just need to finally install a newer gcc myself! 

Are you using the Powertiger Scripts for building? If not, what's the value of OCTOTIGER_THETA_MINIMUM? The default 0.34?

**Comment by dmarce1** [comment]
Gregor

Yes, it's the default.

Thanks
Dominic

**Comment by dmarce1** [comment]
Turns out the thing making the difference isn't the compiler, I was using the "custom" allocator instead of tcmalloc or jemalloc. When I switched back to tcmalloc the problem goes away. I don't know if this means there is a bug in Octo-Tiger that only shows up with the custom allocator or if this means there is a bug with the custom allocator.

**Comment by diehlpk** [comment]
@dmarce1 Can we close this issue?
