### ISSUE TITLE
internal compiler error in release mode

### ISSUE THREAD

**Issue by shibersag** [STEllAR-GROUP/octotiger#325]
## Expected Behavior
Octo-Tiger should compile successfully in Release mode on Queen-Bee.

## Actual Behavior
Compilation of Octo-Tiger in Release mode fails with an internal compiler error:
<pre>In file included from <b>/work/sshiber1/PowerTiger_2/PowerTiger/src/octotiger/octotiger/radiation/rad_grid.hpp:16:0</b>,
                 from <b>/work/sshiber1/PowerTiger_2/PowerTiger/src/octotiger/src/grid.cpp:6</b>:
<b>/work/sshiber1/PowerTiger_2/PowerTiger/src/octotiger/octotiger/unitiger/hydro_impl/reconstruct.hpp:</b> In member function &apos;<b>void hydro_computer&lt;NDIM, INX, PHYSICS&gt;::reconstruct_ppm(std::vector&lt;std::vector&lt;double&gt; &gt;&amp;, const std::vector&lt;double&gt;&amp;, bool, bool, const std::vector&lt;std::vector&lt;double&gt; &gt;&amp;) [with int NDIM = 3; int INX = 8; PHYSICS = physics&lt;3&gt;]</b>&apos;:
<b>/work/sshiber1/PowerTiger_2/PowerTiger/src/octotiger/octotiger/unitiger/hydro_impl/reconstruct.hpp:103:6:</b> <font color="#EF2929"><b>internal compiler error: </b></font>in fold_convert_loc, at fold-const.c:2275
 void <font color="#EF2929"><b>hydro_computer&lt;NDIM, INX, PHYSICS&gt;</b></font>::reconstruct_ppm(std::vector&lt;std::vector&lt;safe_real&gt;&gt; &amp;q, const std::vector&lt;safe_real&gt; &amp;u, bool smooth, bool disc_detect,
      <font color="#EF2929"><b>^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
0x8c6187 fold_convert_loc(unsigned int, tree_node*, tree_node*)
	/work/sshiber1/PowerTiger_2/PowerTiger/src/gcc/gcc/fold-const.c:2274
0x8bccad fold_binary_loc(unsigned int, tree_code, tree_node*, tree_node*, tree_node*)
	/work/sshiber1/PowerTiger_2/PowerTiger/src/gcc/gcc/fold-const.c:9231
0xbf1dea combine_cond_expr_cond
	/work/sshiber1/PowerTiger_2/PowerTiger/src/gcc/gcc/tree-ssa-forwprop.c:378
0xbf28a5 forward_propagate_into_comparison_1
	/work/sshiber1/PowerTiger_2/PowerTiger/src/gcc/gcc/tree-ssa-forwprop.c:460
0xbf601b forward_propagate_into_gimple_cond
	/work/sshiber1/PowerTiger_2/PowerTiger/src/gcc/gcc/tree-ssa-forwprop.c:522
0xbf601b execute
	/work/sshiber1/PowerTiger_2/PowerTiger/src/gcc/gcc/tree-ssa-forwprop.c:2461
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See &lt;https://gcc.gnu.org/bugs/&gt; for instructions.
gmake[2]: *** [CMakeFiles/octolib.dir/src/grid.cpp.o] Error 1</pre>

## Steps to Reproduce the Problem
Using powertiger script to install Octo-Tiger (last commit) on Queen-Bee with mpi, without papi, without apex, in Release mode.
In RelWithDebInfo mode Octo-Tiger compiles successfully.

## Specifications
  - HPX Version: 1.4.0
  - GCC: 7.4.0
  - openmpi: 4.0.0
  - hdf5: 1.8.12
  - boost: 1.68.0
  - jemalloc: 5.1.0
  - hwloc: 1.11.12
  - silo: 4.10.2
  - vc: 1.4.1

**Comment by diehlpk** [comment]
@hkaiser Can you please have a look?

**Comment by hkaiser** [comment]
@shibersag please try a newer compiler as we can't do anything about this (it's a compiler bug).
