### ISSUE TITLE
Empty SILO files caused by call to performance counters.

### ISSUE THREAD

**Issue by dmarce1** [STEllAR-GROUP/octotiger#329]
I ran into the empty SILO output problem while trying to produce init files for V1309. The problem goes away if I comment out line 92 of src/io/silo_out.cpp. Third line from the top, shown here commented out:

void output_stage1(std::string fname, int cycle) {
	printf("Opening output stage 1 on locality %i\n", hpx::get_locality_id());
//	grid::set_idle_rate();
	std::vector<node_location::node_id> ids;
	futs_.clear();
	const auto *node_ptr_ = node_registry::begin()->second.get_ptr().get();
	silo_output_time() = node_ptr_->get_time() * opts().code_to_s;
	silo_output_rotation_time() = node_ptr_->get_rotation_count();
	for (auto i = node_registry::begin(); i != node_registry::end(); ++i) {
		const auto *node_ptr_ = GET(i->second.get_ptr());
		if (!node_ptr_->refined()) {
			futs_.push_back(hpx::async(hpx::launch::async(hpx::threads::thread_priority_boost), [](node_location loc, node_registry::node_ptr ptr) {
				const auto *this_ptr = ptr.get_ptr().get();
				assert(this_ptr);
				const real dx = TWO / real(1 << loc.level()) / real(INX);
				mesh_vars_t rc(loc);
				const std::string suffix = oct_to_str(loc.to_id());
				const grid &gridref = this_ptr->get_hydro_grid();
				rc.vars = gridref.var_data();
				rc.outflow = gridref.get_outflows();
				return std::move(rc);
			}, i->first, i->second));
		}
	}
	printf("Closing output stage 1 on locality %i\n", hpx::get_locality_id());
}

If I don't comment out this line, the call to output_stage1 acts to the caller (line 534 of silo_out.cpp) as if it is completed, even though it never progresses past line 92 (I discovered this by inserting printfs).  Because the caller thinks output_stage1 is complete, it proceeds with the rest of the SILO output process even though no grids have been staged for output, resulting in an empty silo file. Meanwhile output_stage1 is actually stuck in the call to grid::set_idle_rate.

The function grid::set_idle_rate() in src/grid.cpp is

void grid::set_idle_rate() {
	std::string counter_name = "/threads{" + std::to_string(hpx::get_locality_id()) + "/total}/idle-rate";
	hpx::performance_counters::performance_counter count(counter_name);
	idle_rate = count.get_value<double>().get();
	count.reset();
}

I discovered by commenting out lines in this function that the line causing the problem is

	hpx::performance_counters::performance_counter count(counter_name);

I'm not sure why, and what's odd is the very same commit is running right now on queenbee with no output problems at all. 

Hartmut - would you mind looking at this?

-Dominic

**Comment by diehlpk** [comment]
@dmarce1 

HPX needs to be compiled with `-DHPX_WITH_THREAD_IDLE_RATES=ON` and I think this is the same issue @G-071 experienced.
