### ISSUE TITLE
Non-linear scaling on single KNL node

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/octotiger#36]
octotiger doesn't scale to a single KNL node (on cori). 

For more details, see [here](https://github.com/STEllAR-GROUP/octotiger/wiki/Node-Level-Scaling-on-KNL-(on-Cori)).

I'll close this issue as soon as close to linear scaling on a single node is observed (or a good reason is given why this isn't possible).

**Comment by DavidPfander-UniStuttgart** [comment]
Idle rates for the moving stars problem level 1..4 (details see [here)](https://github.com/STEllAR-GROUP/octotiger/wiki/Node-Level-Scaling-on-KNL-(on-Cori)).

level=1 `/threads{locality#0/total}/idle-rate,1,7.579116,[s],6188,[0.01%]`
level=2 `/threads{locality#0/total}/idle-rate,1,5.164179,[s],5836,[0.01%]`
level=3 `/threads{locality#0/total}/idle-rate,1,30.026202,[s],2445,[0.01%]`
level=4 `/threads{locality#0/total}/idle-rate,1,282.282366,[s],1901,[0.01%]`

**Comment by hkaiser** [comment]
That confirms our suspicion that we simply have not enough parallelism in the application to fully utilize all cores on a KNL at this point. Even 19% idle-rate (level=4) is still way too high for good scaling.

**Comment by DavidPfander-UniStuttgart** [comment]
level=5 `/threads{locality#0/total}/idle-rate,1,2852.963514,[s],2641,[0.01%]` on DRAM

l5 with MCDRAM/l6 with DRAM already results in an out-of-memory.

**Comment by khuck** [comment]
David -
You ran out of memory because the defaults for Octotiger create a star that is the same size as the grid, creating lots of cells packed with particle data.  You can control that with the "-Xscale=32 -Odt=0.5" arguments.

(I put the restart files mentioned in this email in the /project/projectdirs/xpress/hpx-lsu-cori-II/restart-files directory)

We need to document this on the wiki, but here is the recommended method for running Octotiger (from an email by Dominic):

```
For test scaling runs, I have created three startup files of the same initial problem at three different maximum levels of refinement. (The problem setup
is a q=0.20 double white dwarf system in near equilibrium)

1) 7 level run with 1513 subgrids
2) 8 level run with 4297 subgrids
3) 9 level run with 11241 subgrids.

(There is about a ~2.7 increase in workload with each step)

I have uploaded the restart files to google drive here: 
https://drive.google.com/drive/folders/0B_Hf1bEwvJEkS21VMzBSdUg1S0k?usp=sharing

The command line to start from these files are are 

./octotiger --hpx:threads 20 -Problem=dwd -Max_level=$LEVEL -Xscale=4.0 -Eos=wd -Angcon=1  -Restart=restart$LEVEL.chk -Stoptime=0.01

where $LEVEL is 7, 8, or 9. Make sure to use the latest octotiger, a couple of the command line options above require the latest version. 

On the SuperMIC computer, with 32 20 node cores, the 8 level problem takes 70 steps and runs in about a minute and a half. Stoptime can be adjusted for longer or shorter runs.
```

**Comment by DavidPfander-UniStuttgart** [comment]
Thanks, Kevin. Experiments with Dominic's new parameters are on their way.

**Comment by DavidPfander-UniStuttgart** [comment]
I added some the scaling for l7 and l8 with Dominic's parameters. Scaling and idle rates look seem to be more or less identical.

Idle rates:
level=7, threads=68 `/threads{locality#0/total}/idle-rate,1,111.275371,[s],3123,[0.01%]
`
level=8, threads=68 `/threads{locality#0/total}/idle-rate,1,327.854486,[s],2863,[0.01%]
`

**Comment by DavidPfander-UniStuttgart** [comment]
Node scaling is somewhat better without GRAV_PAR, but it still is far from perfect. I think two reasons explain this:
* The setup used for the scaling gravs does only a single timestep. Therefore, serial setup und shutdown steps might interfere with the measurement. I'll rerun the scaling experiments with Dominic's updated parameters.
* We need more parallelism on a node. This problem can be solved by again parallelizing across the interactions loop, but this time with a grain size control. I'll also look into this.

**Comment by hkaiser** [comment]
> Node scaling is somewhat better without GRAV_PAR, but it still is far from
> perfect. I think two reasons explain this:
> • The setup used for the scaling gravs does only a single timestep.
> Therefore, serial setup und shutdown steps might interfere with the
> measurement. I'll rerun the scaling experiments with Dominic's updated
> parameters.
> • We need more parallelism on a node. This problem can be solved by again
> parallelizing across the interactions loop, but this time with a grain
> size control. I'll also look into this.

Over the weekend I have done some analysis as well. As it turns out, Octotiger was executing a large amount of very short-executing HPX actions. I applied some changes to the code turning a couple of those actions into directly executing ones. This has reduced the number of executed HPX threads to 30% of the former value and should reduce the pressure on the scheduler significantly.

I have also added some local changes to improve vectorization.

Regards Hartmut
---------------
http://boost-spirit.com
http://stellar.cct.lsu.edu

**Comment by DavidPfander-UniStuttgart** [comment]
Latest results show that scaling has improved a little bit.

I'm re-running the scaling experiments with more timesteps and Xscale=36 right now (still don't know whether that's a good value for Xscale). Scaling should be better with these parameters (and more meaningful).
