### ISSUE TITLE
Can someone add octotiger to a continuous integration system?

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/octotiger#37]
Does someone have a CI system setup where we could add octotiger with some checked parameters, so that we can detect regressions?

**Comment by hkaiser** [comment]
CircleCI is a nice system which is relatively easy to set up. It also nicely integrates with github.

**Comment by DavidPfander-UniStuttgart** [comment]
I think that you have CircleCI on Rostam. Could we use Rostam for CI?

**Comment by hkaiser** [comment]
We use CircleCI here for HPX crash&burn tests: https://circleci.com/gh/STEllAR-GROUP/hpx. On Rostam we use buildbot, which is more difficult to set up.

**Comment by DavidPfander-UniStuttgart** [comment]
Did it myself.

**Comment by hkaiser** [comment]
@DavidPfander-UniStuttgart: thanks for doing that! Where is the CI hosted now?

**Comment by DavidPfander-UniStuttgart** [comment]
Circle CI

**Comment by DavidPfander-UniStuttgart** [comment]
https://circleci.com/gh/STEllAR-GROUP/octotiger
