### ISSUE TITLE
Replace eigenvalus computation with a optimized library?

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/octotiger#39]
Why do we use a own routine for the computation of eigenvlaues here?

https://github.com/STEllAR-GROUP/octotiger/blob/master/src/grid_fmm.cpp#L59

It es maybe faster to use a optimizied routine from some linear algebra library?

Like https://eigen.tuxfamily.org/dox/classEigen_1_1EigenSolver.html

**Comment by hkaiser** [comment]
There is only one way to find out...

**Comment by DavidPfander-UniStuttgart** [comment]
I think that it so far hasn't been observed to be a bottleneck.

**Comment by diehlpk** [comment]
Ok, I think adding this library is not so much work and I will give it a try
