### ISSUE TITLE
lx ly lz fields differ betweens machines when using the STAR scenario

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/octotiger#415]
The fields lx ly lz do not match for runs between different machines (or different gravity kernels for that matter) for the STAR scenario given the parameters used in EOS IPR tests added in #414 .

Suggested actions:
- Long-term: We should either remove the lx ly lz (from what I've gathered during the meetings, these fields aren't used anymore anyway) or fix it. Feel free to discuss whether we should remove those fields or not in this issue!
- Short-term: Some larger & longer running tests with the STAR problem (for parameters see https://github.com/STEllAR-GROUP/octotiger/pull/414/commits/a41ad4437480d734d71e6990c9867254225e6097#diff-27b83eb9acc3063e7a01bc8e47bb986c9cf0bdbe28f76c578ed92793ab1bcc8b ) might be a good idea to check that the problems really does not extend to any other fields. While it didn't seem to the case in the tests added in #414, this was a rather small STAR scenario intended to be suitable for quick local tests during development. @shibersag : Did you notice anything like this (or odd in general) in your tests for the original EOS PR?

**Comment by diehlpk** [comment]
@G-071 Is that still on?

**Comment by diehlpk** [comment]
@G-071 Is that still on?

**Comment by diehlpk** [comment]
cc @dmarce1 and @shibersag

**Comment by diehlpk** [comment]
We will remove these unused files in the feature, but not for the upcoming release.
