### ISSUE TITLE
Document software version for each release

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/octotiger#436]
Have a table with the recommended software versions for each release.

**Comment by shibersag** [comment]
Just as an example, here is what FLASH code is outputting to its log file.
The version number, the c and fortran flags, as well as the parameters used and whether they were changed or used the default value.

Interestingly, it also outputs FLASH counters and timers for each unit which would be also nice to have in Octo-Tiger

 
[sod.log](https://github.com/STEllAR-GROUP/octotiger/files/10724224/sod.log)

**Comment by diehlpk** [comment]
@G-071 I think Spack solves this issue and the ticket can be closed or?
