### ISSUE TITLE
massive memory leak in octotiger

### ISSUE THREAD

**Issue by DavidPfander-UniStuttgart** [STEllAR-GROUP/octotiger#59]
Current master is unusable due to massive memory requirements, possibly due to (a) memory leak(s). However, I don't know how to meaningfully debug this, as I can't get either a valgrind or an address sanitizer build to work (see https://github.com/STEllAR-GROUP/hpx/issues/2746).

Any ideas what we could do?

**Comment by hkaiser** [comment]
What problem have you been running? How to reproduce this? On what platform? Could you be a bit more specific, please?

**Comment by DavidPfander-UniStuttgart** [comment]
I ran our minimal test:
```
./octotiger -t1 -Problem=moving_star -Max_level=3 -Odt=0.3 -Stoptime=0.2 -Xscale=20.0 -Omega=0.1  -Stopstep=9
```
on a Desktop machine.

**Comment by DavidPfander-UniStuttgart** [comment]
I used HPX master and OctoTiger master.

**Comment by dmarce1** [comment]
This isn't the problem I mentioned in the last calls. I was getting it with rotating_star and it turned out to be I was just using an older initialization file.
