### ISSUE TITLE
Octotiger gets stuck on hpx::finalize when only using one thread

### ISSUE THREAD

**Issue by G-071** [STEllAR-GROUP/octotiger#61]
- Octotiger currently gets stuck on hpx::finalize when using the current master branch of octotiger when using a HPX commit from January 22 (29da281b87cfa1171b42f5e2f22caa29b3c4be2d). 
- This problem is not present when using hpx 1.0.0 with other versions of octotiger (branch kernel_refactoring).
- This problem is already present when switching away from hpx 1.0.0 to hpx commit  c9f2c09d9378d920f7d68ce857ca3729014fc601, which is quite a bit older than the other commit I tested.

**Used configuration:** gcc 5.4.0, boost 1.63, 
Vc: Commit 157026d3adf3494922269d11a2e4dede09bf867c (current commit of branch pfandedd_inlining_AVX512)

**Used scenario:**
/octotiger -t1 -Problem=moving_star -Max_level=3 -Odt=0.3 -Stoptime=0.2 -Xscale=20.0 -Omega=0.1 -Stopstep=9 -Disableoutput
This problem does not occur when using -t2 (or more).

Note: Due to #60 I currently cannot test it with a more recent version of HPX.

How can I fix this?

**Comment by hkaiser** [comment]
This sounds to be an HPX problem. Could you report that as an HPX ticket, please?

**Comment by G-071** [comment]
Got fixed with the pull request STEllAR-GROUP/hpx#3172
