### ISSUE TITLE
HPX will be updated to use VC 1.4.1

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/octotiger#80]
This will may affect octotiger and we need to update things there too.

* https://github.com/VcDevel/Vc/releases/tag/1.4.1
* https://github.com/STEllAR-GROUP/hpx/issues/3570

**Comment by hkaiser** [comment]
See STEllAR-GROUP/hpx#3573

**Comment by dmarce1** [comment]
Ok, I'll take care of it.

**Comment by diehlpk** [comment]
I updated ocotiger for usage with the VC 1.4.1 (https://github.com/STEllAR-GROUP/octotiger/tree/updateVC)

There are two files, which need to be updated

* https://github.com/STEllAR-GROUP/octotiger/blob/updateVC/src/common_kernel/kernel_simd_types.hpp
* https://github.com/STEllAR-GROUP/octotiger/blob/updateVC/src/simd.hpp

because there are some changes for the AVC types in the Vc library. 

@dmarce1 and @G-071 could have a look at the new Vc library and update them accordingly?
